export const browserCoreExamples = [
  "openx browser status",
  "openx browser start",
  "openx browser stop",
  "openx browser tabs",
  "openx browser open https://example.com",
  "openx browser focus abcd1234",
  "openx browser close abcd1234",
  "openx browser screenshot",
  "openx browser screenshot --full-page",
  "openx browser screenshot --ref 12",
  "openx browser snapshot",
  "openx browser snapshot --format aria --limit 200",
  "openx browser snapshot --efficient",
  "openx browser snapshot --labels",
];

export const browserActionExamples = [
  "openx browser navigate https://example.com",
  "openx browser resize 1280 720",
  "openx browser click 12 --double",
  'openx browser type 23 "hello" --submit',
  "openx browser press Enter",
  "openx browser hover 44",
  "openx browser drag 10 11",
  "openx browser select 9 OptionA OptionB",
  "openx browser upload /tmp/file.pdf",
  'openx browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "openx browser dialog --accept",
  'openx browser wait --text "Done"',
  "openx browser evaluate --fn '(el) => el.textContent' --ref 7",
  "openx browser console --level error",
  "openx browser pdf",
];
